#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then set -o xtrace; fi

all_name='[all]'

d_artist() {
  beet ls -af '$albumartist' | uniq | shuf | dmenu -i
}

d_album() {
  local albumartist="$1"
  local albums

  mapfile -t albums < <(beet ls -a original_year+ -f "\$album [\$releasegroupdisambig]" "albumartist:$albumartist" | sed 's/\[\]//')
  if (( ${#albums[@]} > 1 )) ; then
    {
      printf '%s\n' "${albums[@]}"
      printf '%s\n' "$all_name"
    } | dmenu -i
  else
    # We only have one album, so just use that
    printf '%s\n' "${albums[0]}"
  fi
}

case "$1" in
  artist)
    albumartist=$(d_artist) || exit 1
    album=$(d_album "$albumartist") || exit 2
    disambig=$(echo ${album} | sed -E 's/.*\[(.*)\]$/\1/') # Hittar ingenting
    album=$(echo ${album} | sed -e "s/\[$disambig\]\$//")

    # TODO Shift+return to append?
    mpc clear
    if [[ $album == "$all_name" ]]; then
      beet play -a 'albumartist:=~'${albumartist}
    else
      if [[ ${album} == ${disambig} ]]; then
        echo "${disambig} : ${disambig}"
        beet play -a "albumartist:=~${albumartist}" "album:=~${album}"
      else
        echo "${disambig}"
        beet play -a "albumartist:=~${albumartist}" "album:=~${album}" "releasegroupdisambig:=~${disambig}"
      fi
    fi

    mpc play >/dev/null
    ;;
esac
