#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then set -o xtrace; fi

all_name='[all]'

d_artist() {
  mpc list albumartist | shuf | dmenu -i
}

d_album() {
  local albumartist="$1"
  local albums

  mapfile -t albums < <(mpc list album albumartist "$albumartist")
  if (( ${#albums[@]} > 1 )) ; then
    {
      printf '%s\n' "$all_name"
      printf '%s\n' "${albums[@]}" | sort -f
    } | dmenu -i
  else
    # We only have one album, so just use that
    printf '%s\n' "${albums[0]}"
  fi
}

case "$1" in
  artist)
    # TODO This definitely does not work for Weezer
    albumartist=$(d_artist) || exit 1
    album=$(d_album "$albumartist") || exit 2

    # TODO Shift+return to append?
    mpc clear
    if [[ $album == "$all_name" ]]; then
      mpc find albumartist "$albumartist" | sort | mpc add
    else
      mpc find albumartist "$albumartist" album "$album" | sort | mpc add
    fi

    mpc play >/dev/null
    ;;
  album)
    album=$(d_album "$albumartist") || exit 1

    mpc clear
    if [[ $album == "$all_name" ]]; then
      mpc find albumartist "$albumartist" | sort | mpc add
    else
      mpc find album "$album" | sort | mpc add
    fi

    mpc play >/dev/null
    ;;
esac
